### ISSUE TITLE
Ability to run tests inside a docker container themselves

### ISSUE THREAD

**Issue by wngr** [testcontainers/testcontainers-rs#129]
Hey,

the current approach of this library assumes that `cargo test` is executed on the host system running docker. For having a reproducible environment, it makes sense to run the tests themselves inside a docker container. To be able to have those tests spin up and access other containers, we'd need to:
1. Be able to access the docker socket from within the container (and have `docker-cli` installed)
1. Make sure the networking is properly set up, e.g. same docker network / bridging
1. Ability to get the IP of the created container --> `docker inspect` has it

My proposed approach would be to create another `Client` and implement _2_ and _3_ as enumerated above. Obviously, to be able to use it, the library users needs to make sure _1_ is properly set up.

What do you think about this approach? Would you be willing to accept a PR implementing the above?

**Comment by D4nte** [comment]
Maybe look into the shiplift crate so you don't create a docker api client from scratch.

**Comment by thomaseizinger** [comment]
> What do you think about this approach? Would you be willing to accept a PR implementing the above?

Yes definitely!
That is the direction we would want to take this library in, we just didn't have any needs for it so far :)
We would definitely accept a PR for this!

**Comment by wngr** [comment]
> Maybe look into the shiplift crate so you don't create a docker api client from scratch.

Thanks for the hint, will give it a spin then!

**Comment by DDtKey** [comment]
I think this should be possible with current state of `testcontainers`. We don't use `cli` client anymore and there is a [detection of host inside of container](https://github.com/testcontainers/testcontainers-rs/blob/8f4279fcef8279ca1ac2bf9fdb8793c28973347d/testcontainers/src/core/client.rs#L368-L387)

So I'm going to close the issue because of outdated state, but if you feel it still doesn't work, feel free to re-open or create a new one.

Thank you!
