### ISSUE TITLE
add possibility to start container in host network

### ISSUE THREAD

**Issue by pronvis** [testcontainers/testcontainers-rs#201]

**Comment by invis87** [comment]
[PR](https://github.com/testcontainers/testcontainers-rs/pull/202)

**Comment by TheButlah** [comment]
I'm in a situation where I'm running my CI inside of docker, and have bind-mounted the host daemon's socket so that I can create sibling containers instead of using docker-in-docker. In this sense, when testcontainers creates a container, it makes that container a sibling container to the currently executing CI container, rather than a child container. This means that I cannot access the new container via `localhost:1234`, since sibling containers don't share a docker network by default.

Would #202 or a similar PR address this use case?

**Comment by thomaseizinger** [comment]
The network approach should work but I think the _real_ solution would be something like this: https://github.com/testcontainers/testcontainers-rs/pull/141

That issue pretty much stalled unfortunately. The feature is not a priority for us so I can't really allocate much time to it :/
However, like I said in the linked PR, I am more than happy for this to be realized but it would need someone else to push it forward :)

**Comment by 0xDjole** [comment]
Oh damn...I would really like this...so I can test TiKV database.

**Comment by DDtKey** [comment]
Since it's already possible to start container in host network, I'm going to close the issue.

But I'll create a new one for discussed here approach to run tests in a container
