### ISSUE TITLE
Do not remove docker network if `KEEP_CONTAINERS=true`

### ISSUE THREAD

**Issue by invis87** [testcontainers/testcontainers-rs#224]
https://github.com/testcontainers/testcontainers-rs/blob/40dcfb82c5c9670e6254e8f2bdf19ac5b215f6e8/src/clients/cli.rs#L232

Do not remove docker network if `KEEP_CONTAINERS=true`. Otherwise it is impossible to start conrainers that was created during test:
```
> docker start {container_name}

Error response from daemon: network {network_id} not found
```

**Comment by thomaseizinger** [comment]
Interesting!

The functionality behind `KEEP_CONTAINERS` was originally built so that you can inspect the logs and other container state after a test run for debugging purposes. Restarting them was never really in scope as you could just re-run the test to have new containers.

Currently, we only delete the network if we also created it at the beginning. That allows us to keep it ephemeral and at the same time allows the user to re-use a network that already exists. If we were to not delete it at the end, then we would "leak" the network in the case where `KEEP_CONTAINERS` is true. That might be a surprising behaviour.

What do you think?

**Comment by invis87** [comment]
> If we were to not delete it at the end, then we would "leak" the network in the case where KEEP_CONTAINERS is true
The same is about containers. They "leak" :) I think it is fine, when you know what you are doing :) Maybe we can write this info to console. Something like `network net-299 was created during test run, but will not be deleted cause of KEEP_CONTAINERS flag`

> Restarting them was never really in scope as you could just re-run the test to have new containers.
I am inspecting database after tests, so container should be start again.

**Comment by thomaseizinger** [comment]
> The same is about containers. They "leak" :)

That is true but at least those can be cleaned up with a single command (I usually use `docker rm -f $(docker ps -aq)`). Deleting docker networks as well now requires additional commands.

I am a bit divided here. Do we have any alternatives as to how we could manage docker networks and container lifetimes that avoids this problem?

**Comment by invis87** [comment]
`docker network rm {net_name}` - simple too :)

> Do we have any alternatives as to how we could manage docker networks and container lifetimes that avoids this problem?

It is not about lifetimes as I can see. It is about "start container after tests, to be able to inspect it internal state (Database state for example)

**Comment by thomaseizinger** [comment]
> `docker network rm {net_name}` - simple too :)

I never said it was hard - just that it requires an additional command and it might not be obvious to the user because they are only specifying `KEEP_CONTAINERS=true`.

> It is not about lifetimes as I can see. It is about "start container after tests, to be able to inspect it internal state (Database state for example)

My apologies, I used the word "lifetime" here ambiguously. I wasn't talking about Rust's lifetimes per se but about the fact that we manage the container's "life" as part of testcontainers.

I remember now that I had a usecase like yours before. The way I solved it was that I just set a break-point at the end of the test and thus kept the container alive. Would that work for you?

**Comment by invis87** [comment]
Heh))
Actually I still use my forked branch, so I just add 
```rust
        if !keep_container {
            self.rm()
        }
```
in Drop for Network. 
But I think solution like `break-point at the end of the test and thus kept the container alive` is not good at all. For example I have no idea how to add break points to rust programs at first, and second - it looks like crunch.

**Comment by thomaseizinger** [comment]
> But I think solution like `break-point at the end of the test and thus kept the container alive` is not good at all. For example I have no idea how to add break points to rust programs at first, and second - it looks like crunch.

If you use Intellij Clion, it is a single click next to the line number you want to break on.

In any case, I am not quite sure how to handle this best. I can see why I can be useful but I am worried that it is experienced as not cleaning up properly if people don't fully understand how these things interplay.

If you create docker network with the same name again, are you able to start the containers?

**Comment by invis87** [comment]
> If you create docker network with the same name again, are you able to start the containers?

nope, containers using network ID which is randomly generated

**Comment by thomaseizinger** [comment]
FYI: I've had an idea recently that could solve this without being too surprising for the user: https://github.com/testcontainers/testcontainers-rs/issues/235

**Comment by thomaseizinger** [comment]
Actually, I think with the env variable being renamed, I might be coming around to your view on this issue :)

Let's continue this discussion in #235.
