### ISSUE TITLE
Timeline for v0.13.0?

### ISSUE THREAD

**Issue by j4ckcyw** [testcontainers/testcontainers-rs#276]
Looks like there are some api changes since v0.12.0. Is there a timeline for next release?
https://docs.rs/testcontainers/0.12.0/testcontainers/

**Comment by thomaseizinger** [comment]
There is no specific timeline but the async API just merged and it still [has some bugs](https://github.com/testcontainers/testcontainers-rs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) that needed to be ironed out before it can be released. Help on that would btw be very appreciated :)

Either we fix those bugs (and do more testing to make sure there aren't any others) or we exclude the async API from the next release. Is there a specific functionality you would already like access to? Maybe we can backport something to a smaller release if it is really urgent.

**Comment by j4ckcyw** [comment]
Sure. What I'm trying to do is to start a image of localstack: https://github.com/localstack/localstack

My current workflow would be simply to run that as a process in another tab, while I run `cargo test`. Some time later, I would embed this into the test so it'll always start with a clean slate and can be run as part of CI/CD. 

I was curious about v0.13.0 because:
1. there is some change in API and I would like to delay the work to get it working and upgrade
2. crate.io doesn't offer much documentation so I end up looking at the github examples, and some of them are newer than last release

**Comment by thomaseizinger** [comment]
I am afraid I won't have much time to work on testcontainers in the next weeks.

Are you planning to release your crate to crates.io? Because if not, then you can always use a git dependency onto the latest HEAD of `dev` to use the very latest version.

I would only advise to stay away from the `shiplift` client for now because it is still buggy and in development. The `Cli` client however is reliable and fairly well tested so I wouldn't have any concerns in using that fresh off `dev`.

Would that work for you?

The API changes since 0.12 aren't a whole lot. Except for the shiplift client, it is basically these three: https://github.com/testcontainers/testcontainers-rs/pull/259, https://github.com/testcontainers/testcontainers-rs/pull/258, https://github.com/testcontainers/testcontainers-rs/pull/253. Even those changes are relatively minor so I wouldn't worry too much about building on top of an "old" interface.

As you can see from [this](https://github.com/testcontainers/testcontainers-rs/pull/253/commits/0d462353e3808238a9658b6d330e4931e1ca0700#diff-9b8231ac30a94824764ceb5647c2ee9a6b551d79efe46279278ff2e15efdab3e) diff, upgrading a single image was quite trivial.

I'll leave it up to you but I would like to avoid backporting things because it is just extra work and if I get time to spend on testcontainers, I'd rather iron out some bugs instead :)

**Comment by j4ckcyw** [comment]
Make sense to me. I'll play around with the diff you linked above. Feel free to close this.

**Comment by thomaseizinger** [comment]
Closing favor of creating a milestone that tracks remaining things: https://github.com/testcontainers/testcontainers-rs/milestone/8
