### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#347]
Help in maintaining this project would be greatly appreciated.

Please comment if you are interested or ping me on matrix: https://matrix.to/#/@thomaseizinger:matrix.org

**Comment by marlon-sousa** [comment]
Hello,

Could you elaborate on what is involved omn this?

As far as I understand the infrastructure so to say for the project is pretty much done, with either new images or small improvement on existing images functionality being the most likely features to be integrated.

For example, I need rabbitMQ for my project and as far as I could understand image is on master but not yet published.

A simple question though is this: how can I help to publish this one to crates.io (e.e what is involved on that process)?

May be by specifing small baby steps you can find a group of people to help.

I see rust as a brilliant language not only for systems development but also for microservices and other domains. Projects such as this one and cucumber, as well as other testing frameworks and also mock servers and such are key to help the eco system to grow and make it easier for new adopters to come. I am getting very afraid that this risks not succeeding at all because so many of these important projects did not see any release in a long period.

Not to blame you, everyone has their lifes, question here is wht can we do to help to publish at least, as a first step, stuff already on master as a first step.

**Comment by thomaseizinger** [comment]
I am actually just working on publishing a release :)

We are using git flow in this repository, meaning releases are cut by branching off a `release/x.y.z` branch from `dev` and pointing it to `master`. Once merged into `master`, a release will automatically be uploaded to crates.io!

See the release PR here: https://github.com/testcontainers/testcontainers-rs/pull/350

> As far as I understand the infrastructure so to say for the project is pretty much done, with either new images or small improvement on existing images functionality being the most likely features to be integrated.

More or less. The latest release includes a massive re-write of many parts that should make it much easier to define new images outside of this repo, i.e. the boilerplate required goes down significantly. That work is not fully complete yet, there is still more that can be done :)

In the last release, I've also tried to trim down the public API to make breaking changes less likely (so we can eventually comfortably hit 1.0.0). I haven't looked into things in a while but I expect that we can also do more on that front!

**Comment by mervyn-mccreight** [comment]
I'd love to volunteer for this - is there any "official" communication channel for this project where I'd have to join?

**Comment by thomaseizinger** [comment]
There is no official communication channel other than Github issues. I guess I could create a Matrix room :)

**Comment by thomaseizinger** [comment]
I've created a matrix room: https://matrix.to/#/#testcontainers-rs:matrix.org

**Comment by kiview** [comment]
@mervyn-mccreight Going ahead, we should communicate in the Testcontainers Slack channel, feel free to join 🙂 
http://slack.testcontainers.org/

**Comment by thomaseizinger** [comment]
I am closing this for now as "resolved" because the immediate need for people helping out is being addressed.

**Comment by matthiasbeyer** [comment]
I'd like to see this reopened as there are quite a few dependabot updates which are not even merged...

It seems there's still need for maintainers here, is there?

**Comment by thomaseizinger** [comment]
@matthiasbeyer and I had an email conversation and he will try to help out with some of the maintenance work in here! :tada:

**Comment by DuncanConroy** [comment]
I'd also be happy to help out.

**Comment by thomaseizinger** [comment]
> I'd also be happy to help out.

Thank you!

The most pressing need is a timely response to user issues, followed by active development. In particular, https://github.com/testcontainers/testcontainers-rs/issues/386 would solve some long-requested issues and overall make the library easier to use.

The thing is, I am no longer an active user of the library myself, thus it would be better if someone with more stake could actively drive the development and generate ideas such as the above.
