### ISSUE TITLE
is there any way to pass "platform" parameter when running docker images?

### ISSUE THREAD

**Issue by horacimacias** [testcontainers/testcontainers-rs#500]
for example,

```bash

docker run --platform linux/arm64/v8 ....
```

**Comment by endertunc** [comment]
I don't think so but this should fairly easy to add.

**Comment by thomaseizinger** [comment]
Containers aren't virtual machines, so unless your host has x64 code emulation support, this doesn't even work right?

That sounds very niche to me.

Also, docker's multiplatform images are just manifests that point to other images. You should be able to reference the actual x64 image and thus force execution of that one instead of having docker auto-pick a platform based on the manifest only to override that again.

**Comment by horacimacias** [comment]
thanks.
I'm having some issues with a particular image and forcing the platform does seem to help but I agree it may be a niche scenario. If I'm able to specify the platform then my tests rely less in environment setup (even if issues would only happen in a very small subset of scenarios).
I'll try using the x64 reference as you suggested; perhaps this gives me the same without needing any changes.

**Comment by thomaseizinger** [comment]
Cool, hope you find something that works! :)

**Comment by laz-001** [comment]
@thomaseizinger , you server docker, so just respect `DOCKER_DEFAULT_PLATFORM` env setting, and all good.

Currently, you break things.
